class CommandError(Exception):
    """Raise from subcommands to report back to the user"""
